
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufznrykdisasqfzxgwte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmem5yeWtkaXNhc3Fmenhnd3RlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NTcxNTQsImV4cCI6MjA2MzEzMzE1NH0.1ttU5-YfzrgTFJ_CdgKcu3tY5VFC6wnJuDy--cVzyX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
